### ISSUE TITLE
破碎大道当期合约（3.17~3.31）少了三级大斧

### ISSUE THREAD

**Issue by guoh064** [Houdou/prts-map#11]
是如下这个合约：所有<碎岩者>和<碎岩者组长>的生命值提升100%，防御力增加450，攻击力提升70%，且获得隐匿效果

**Comment by Houdou** [comment]
咦，看来是手滑漏了。。。
这些数据都是手打进去的，所以可能会有一些纰漏，实在不好意思

**Comment by Houdou** [comment]
而且我发现训练场和每日轮换的数据不一样。。。

**Comment by guoh064** [comment]
训练场和每日轮换确实不一样。
而且看这个情况，下一周的每日轮换和这一周的每日轮换也会不一样。（参考上次危机合约）
（训练场也就图一乐，真要图一乐还得看日替）
所以维护起来也挺麻烦的……辛苦了
感觉相对来说研究破碎大道（常驻图）的人会多一些。
日替图的tag可以想想别的办法？看看能不能从解包数据里提前看到当天要更什么轮换？（不是很懂原理所以可能说了外行话）

**Comment by Houdou** [comment]
要是合约在解包里那早就传开了，摊手
不过大部分合约都是在那个列表里，当期找不到的话，关掉当期去找找一般都有
