### ISSUE TITLE
路线重叠导致的路线混乱

### ISSUE THREAD

**Issue by Yanstory** [Houdou/prts-map#14]
很多地图一开始就有大量敌人出现，这时候路线就会混杂在一起
像GT-8的大鲍勃的路线就几乎无法看清，建议可以用一个选项强制只显示单个敌人的路径，或者定位到当前敌人时只显示这个敌人的路线

**Comment by Houdou** [comment]
是的，这个feature我很早就计划了。。。
但没有安排上 😂 我看这几天应该可以抽空做一下

**Comment by Houdou** [comment]
Done
