### ISSUE TITLE
S7-2 部分敌方路线错误

### ISSUE THREAD

**Issue by DCxDESIGN** [Houdou/prts-map#15]
如题，第14 19 31 36波次的敌人行进路线应为从右下方红门起，沿最下方一条直线，直接进左下方蓝门，请核实并修复，谢谢

**Comment by Houdou** [comment]
我检查了一下，是因为地图预置的地雷引起的寻路bug，正在修复

**Comment by DCxDESIGN** [comment]
好的谢谢，地雷应该设置成不挡路w

**Comment by Houdou** [comment]
@DCxDESIGN 
在0.13.2修复了~
