### ISSUE TITLE
Wrong enemy stats in OF-EX-4

### ISSUE THREAD

**Issue by a-casual** [Houdou/prts-map#16]
In OF-EX-4 (https://map.ark-nights.com/map/a003_ex04) spawn index 4~5 is a Hound Pro (猎狗pro) with displayed ATK stat 260.

In fact, this doggo bites much harder than that, harder than spawn 1 Infantry Leader (步兵组长) with 330 atk. This is easy to see if you deploy somebody with about 280-330 def, e.g. Plume.

I think this is because there are 2 different Hound Pro mobs, and a wrong one is displayed.
From https://aceship.github.io/AN-EN-Tags/akenemy.html
- level 0: 260 atk, 1700 hp
- level 1: 460 atk, 2900 hp

Maybe other maps have similar issues with upgraded versions of the same mob.

**Comment by Houdou** [comment]
😮 I'm sorry for any inconvenience.
You are correct, it's level 1 hound in the map data.

After reviewing the code, I found that I missed to pass this `level` to the enemy data query for more than half year 😂 
Thank you so much for pointing out the issue!

**Comment by Houdou** [comment]
@a-casual 
Fix deployed~ It should be 0.13.2 now.
Please force refresh (Ctrl + F5) if it's still in the old version

**Comment by a-casual** [comment]
Thank you for the super quick fix! I can see the strong version now.

**Comment by Houdou** [comment]
🤪 
Wait a sec, I found that the level 1 data only override some value when switch to level 1.

Let me fix it ...
