### ISSUE TITLE
CC Area59 tags don't match in-game description

### ISSUE THREAD

**Issue by a-casual** [Houdou/prts-map#17]
Axeman tags according to in-game description provide +80% hp and +150% hp correspondingly:
![image](https://user-images.githubusercontent.com/57562727/85184862-b8e15a80-b291-11ea-8f4e-0021cd647ceb.png)

In prts-map they don't:
![image](https://user-images.githubusercontent.com/57562727/85184899-f5ad5180-b291-11ea-83e3-d288aa71cfc5.png)

**Comment by Houdou** [comment]
Oops...
Thank you for pointing out the mistakes. Sorry for any inconvenience.
Have fixed the data.

**Comment by Houdou** [comment]
@a-casual
Just realized I haven't translate the description for all the languages...
Hope that didn't trouble you too much😂
