### ISSUE TITLE
集成战略-无主巨物关卡，切换第一个巨像路线图无效

### ISSUE THREAD

**Issue by DSLM** [Houdou/prts-map#20]
如题，这一关巨像有可能在右边的，但是路线图始终显示在左边

**Comment by Houdou** [comment]
@DSLM 
上午应该已经更新了一个版本解决了这个问题，可以确认一下版本是不是 0.18.1
版本不对可以尝试 Ctrl F5 刷新

**Comment by DSLM** [comment]
已解决
