### ISSUE TITLE
什么时候能优化一下手机端的使用体验

### ISSUE THREAD

**Issue by jasonfall** [Houdou/prts-map#24]
PRTS.MAP目前什么都好，就是太大了，而且明明手机分辨率比我的笔记本大，但是显示却不全，看起来非常麻烦，要是什么时候能优化一下手机端的体验就好了。

**Comment by Houdou** [comment]
手机分辨率是高。。但是屏幕面积还是太小了，所以一般手机浏览器会用一种缩小过的分辨率来渲染页面
硬改也是能和电脑上一样用的，但是图标什么的就太小了……

加上…………时间不太够用就只能这样了（（抱歉
