### ISSUE TITLE
次生敌人数据与路线显示

### ISSUE THREAD

**Issue by Darkbblue** [Houdou/prts-map#28]
上次联动SS和本次遗尘漫步SS都出现了次生敌人，但是这类敌人的数据和路线都无法直接查看  
在联动SS中，次生的虫子的路线与原敌人一致，但是本次SS的无人机应该是独立的路线，若无法查看还是容易造成困扰  
不知道有无可能增加次生敌人的展示功能

**Comment by Houdou** [comment]
无人机是没有线路的，目的地是敌人动态指定的。只能得靠自己了（

**Comment by Houdou** [comment]
不过无人机本来也不会进家，过一段时间就没了。
你当成炮兵打出来的飞弹理解就好了

**Comment by Darkbblue** [comment]
> 无人机是没有线路的，目的地是敌人动态指定的。只能得靠自己了（

确实，活动解锁之前我理解错了……
