### ISSUE TITLE
能增加一个当前敌人计数吗？

### ISSUE THREAD

**Issue by mrl998** [Houdou/prts-map#3]
指示这一波是第几个敌人，方便跟游戏里的击杀数对应

**Comment by Houdou** [comment]
恩？是显示BUG么，这两个地方的数字都是对应的第几个敌人
<img width="784" alt="image" src="https://user-images.githubusercontent.com/6690811/63853582-ada10380-c9cd-11e9-86c8-1ca5968eded1.png">

**Comment by mrl998** [comment]
> 恩？是显示BUG么，这两个地方的数字都是对应的第几个敌人
> <img alt="image" width="784" src="https://user-images.githubusercontent.com/6690811/63853582-ada10380-c9cd-11e9-86c8-1ca5968eded1.png">

我指的是最下面出兵列表里，抱歉没表达清楚。

**Comment by Houdou** [comment]
这个应该容易加，回头看看UI上怎么样

**Comment by Houdou** [comment]
Done
