### ISSUE TITLE
风雪过境地图打不开

### ISSUE THREAD

**Issue by Yjun233** [Houdou/prts-map#32]
其他的都打得开，就这次活动的打不开

**Comment by Houdou** [comment]
不好意思，白天有点忙，自动更新推送上去的
应该是有新的地砖类型需要处理。晚上应该就能修复了

**Comment by Houdou** [comment]
现在应该好了

**Comment by Yjun233** [comment]
试了下还是打不开，是要再等一会儿么？

**Comment by Houdou** [comment]
现在的版本是0.29.1嘛？
试试ctrl f5刷新呢
或者试试换一下 map.ark-nights.com / mapcn.ark-nights.com
