### ISSUE TITLE
希望能选择改变显示坐标的方式（最左上角格子是0,0）

### ISSUE THREAD

**Issue by Lancarus** [Houdou/prts-map#37]
希望能选择改变显示坐标的方式（最左上角是0,0）。方便匹配[maa战斗流程协议](https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/dev/docs/%E6%88%98%E6%96%97%E6%B5%81%E7%A8%8B%E5%8D%8F%E8%AE%AE.md)
![image](https://user-images.githubusercontent.com/34369130/178772963-3dafc0ec-9f04-44e3-8a5c-b6ddb75ee9d6.png)
![image](https://user-images.githubusercontent.com/34369130/178772629-f12b6fe3-7ecf-4d93-9441-220f67d6e199.png)

**Comment by Houdou** [comment]
额。。。游戏原始数据就是从左下开始的哦
这里不太可能改变默认展示方式
是有什么需求要从 Map 这边导出数据嘛？还是方便玩家抄写坐标？

只是展示的话，可以看加一个开关选项

**Comment by Lancarus** [comment]
方便抄写坐标～
因为那个协议的左边就是左上角是原点，先横后纵，每次设计打法的时候，还要一个一个的数，有点头痛≥﹏≤只是展示就可以～

---原始邮件---
发件人: "Travis ***@***.***&gt;
发送时间: 2022年7月18日(周一) 上午10:59
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Houdou/prts-map] 希望能选择改变显示坐标的方式（最左上角格子是0,0） (Issue #37)




 
额。。。游戏原始数据就是从左下开始的哦
 这里不太可能改变默认展示方式
 是有什么需求要从 Map 这边导出数据嘛？还是方便玩家抄写坐标？
 
只是展示的话，可以看加一个开关选项

**Comment by Houdou** [comment]
加好了，设置里可以切

**Comment by Lancarus** [comment]
太感谢了(^v^)



---原始邮件---
发件人: "Travis ***@***.***&gt;
发送时间: 2022年7月18日(周一) 中午12:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Houdou/prts-map] 希望能选择改变显示坐标的方式（最左上角格子是0,0） (Issue #37)




 
加好了，设置里可以切

**Comment by yuanyan3060** [comment]
> 

大佬牛逼，我全责

**Comment by MistEO** [comment]
感谢作者大大~
