### ISSUE TITLE
MAA 模式下部分地图 x, y 坐标反了

### ISSUE THREAD

**Issue by MistEO** [Houdou/prts-map#38]
![image](https://user-images.githubusercontent.com/18511905/179720635-5760d493-85fc-466c-ab2b-aeab4f9c49b1.png)

来自群友反馈，这个是新活动关卡 TC-1

**Comment by nightofknife** [comment]
给玛丽补个图
![TC-1](https://user-images.githubusercontent.com/73384329/179722423-3be9d7d0-dd07-4597-951a-cb040b100037.png)

**Comment by yuanyan3060** [comment]
屑玛丽！

**Comment by Houdou** [comment]
啊咧只有部分？原来前面是横坐标啊（

**Comment by Houdou** [comment]
修好了

**Comment by yuanyan3060** [comment]
> 修好了

牛蛙 带带泰迪
