### ISSUE TITLE
可以在 url 中加入坐标显示方式的参数嘛？

### ISSUE THREAD

**Issue by MistEO** [Houdou/prts-map#39]
例如 <https://map.ark-nights.com/map/lt_01_01?display=maa>

我们打算在 MAA 的 [作业分享平台](https://prts.plus) 上加入类似的直链让用户可以直接跳转过来使用

感谢大佬~

**Comment by Houdou** [comment]
加了，用 `?coord_override=maa`
所有页面都可以用
