### ISSUE TITLE
希望完善敌方信息

### ISSUE THREAD

**Issue by qjzcj2008** [Houdou/prts-map#4]
希望能增加敌方的防抗信息方便云的时候挑选打本阵容，我看引用的数据里有enemy_database，不知道为什么一开始没有把这些数据展示出来，还是说因为有些关卡会对这些数值进行覆写，要进行展示的话逻辑会比较复杂？不知道以后能不能增加这个功能。

**Comment by Houdou** [comment]
是的，关卡里会有一些数据要覆盖原始的database里的值。
需要一点时间来安排UI位置，努力抽空做一下
