### ISSUE TITLE
ISW-DF再启新篇确定剧场组装体为34000血量么

### ISSUE THREAD

**Issue by Creeperac** [Houdou/prts-map#40]
PRTS.map中显示是与乌萨斯的渴求一样的34000血量 但是似乎实际数据是24000诶
![图片](https://user-images.githubusercontent.com/110230535/181735482-7bea4021-4c08-448c-85e0-1b6fd312c3c7.png)

**Comment by Houdou** [comment]
恩？等一下
我这看着确实是 24000 呀，是不是最近更新数据了。还是老版本？

![image](https://user-images.githubusercontent.com/6690811/181746429-9ee2a48b-da32-4df6-83de-0614debd45dc.png)

**Comment by Houdou** [comment]
我翻了今年所有版本的数据……
这里都是 24000 呀……

**Comment by Creeperac** [comment]
> 我翻了今年所有版本的数据…… 这里都是 24000 呀……

前几天和今上午我看着都是34000 但是刚刚变成24000了 可能是数据没更新？

**Comment by Creeperac** [comment]
> 我翻了今年所有版本的数据…… 这里都是 24000 呀……

好 我刚刚看了一下 如果你去乌萨斯的渴求里点一下剧场组装体的路线 再回到再启新篇点一下就会变成34000

**Comment by Creeperac** [comment]
> 我翻了今年所有版本的数据…… 这里都是 24000 呀……

如果你点过乌萨斯渴求的数据那么观察和雪山上的来客也会变成34000 大概是bug

**Comment by Creeperac** [comment]
> 我翻了今年所有版本的数据…… 这里都是 24000 呀……

大概试出来了 如果你点过乌萨斯的渴求的数据那么这个页面的所有关于挡四哥的数据都会变成34000 关闭页面再打开就会恢复正常

**Comment by Houdou** [comment]
确实，能复现了
我研究一下什么情况

**Comment by Houdou** [comment]
修好了
