### ISSUE TITLE
一些问题与建议

### ISSUE THREAD

**Issue by MegaOwIer** [Houdou/prts-map#43]
Bugs
1. 目前【集成战略】页面下并没有显示初代小刻肉鸽的关卡路线图（虽然也无伤大雅）。
2. 目前【别传】页面中有显示初代危机合约、联机、初代爬塔等内容（应该是改的时候没删干净？）。

Suggestions
1. 目前二级分类下使用矩形卡片展示的交互体验不是很好，在没有图标的情况下使用类似选关页面的列表形式可能更加高效。
2. 【资源收集】关卡相对固定，且每个子类下关卡数量很少，建议点进【资源收集】后直接展示全部关卡而非进一步选择分类（悖论模拟同理）。
3. 建议以【Side Story】和【故事集】区分活动关卡而非像游戏客户端那样以【插曲】和【别传】区分。
4. 建议将活动关卡的各个子分类以“首次开启时间”为关键字排序。
5. 建议将现有的【全关卡】页面功能改为仅显示当期非常驻关卡（活动+剿灭之类的？）而非将其移除。（另外该页面翻译中提到的 deprecated 一般指“弃用”，表达“移除”用 removed/deleted 可能更好）

Reature Request
1. 添加关卡搜索功能。

**Comment by Houdou** [comment]
其实我不想拆别传和插曲那些的主要原因是，我没有其他 logo ，也没时间设计新的（
至于分类问题，有一些是打算跳过那个单独选区的，不过那就没有炫酷的动效了（x   有空再看怎么做吧
新地图的页面我本来打算放到分区上做个 new 啥的标记，不过好像单独放个页面也行，省得找
顺便，我就是 deprecate 而已，页面会保留的

搜索也会做的，但是最近有些其他事情要忙，没啥时间整，可能得看十月份了

**Comment by MegaOwIer** [comment]
UPD:
[Bug] 现在合约里根据词条改变出现时机的敌人貌似都不显示的（可能是1016更新的问题）
[Suggestion] 建议在地图信息里加上进入关卡后才出现的装置（如肉鸽骑士/某些合约地图中的箱子）
