### ISSUE TITLE
能不能把地图数据导出

### ISSUE THREAD

**Issue by Lingyu-Luo** [Houdou/prts-map#44]
类似导出成
map_name="……"
map[][]={{0,0,1,1,2,2,1,1,0,0},
……}//0表示地面不可部署,1表示地面可部署……以此类推   特殊装置也用序号表示
每个敌人分别记录生命、防御、攻击、法抗、出现时间、哪个门、移速、各种抗性等  再放入一个列表中

如果能实现的话就能训练自动打图了（）

**Comment by Houdou** [comment]
请直接参考 kengxxiao 大佬的 repo 吧。
没必要重新定义新的 schema 了
https://github.com/Kengxxiao/ArknightsGameData
