### ISSUE TITLE
集成战略中普通和紧急的分歧怪会被两边同时统计进怪物中

### ISSUE THREAD

**Issue by runswell** [Houdou/prts-map#45]
如原始部落这张图, 普通固定开场是红鳄鱼, 紧急固定开场是石头人, 但是红鳄鱼和石头人会被普通和紧急同时显示在怪物中, 导致怪物数量不对
之前微博私信提到的怪物数字不对的问题就是这个原因

**Comment by Houdou** [comment]
之前没处理 hiddenGroup，现在应该好了

![image](https://user-images.githubusercontent.com/6690811/196048774-207ada32-c4f9-459a-a62b-3c8301160d53.png)
