### ISSUE TITLE
Chapter 10 Global/EN server translations

### ISSUE THREAD

**Issue by grantwwu** [Houdou/prts-map#46]
Hello!

Thank you for your hard work on PRTS Map.

Arknights Chapter 10 has been released to the global server. Could you pull in the translations?

Thanks!

你好！

谢谢你们对 PRTS Map 的功劳。

国际版本的第10章出来了。能不能麻烦你们把翻译更新一下？

多谢！

**Comment by grantwwu** [comment]
I see the translations now. There isn't a changelog entry for it, but that's okay.

**Comment by Houdou** [comment]
> I see the translations now. There isn't a changelog entry for it, but that's okay.

@grantwwu 
🙈  Sorry, havn't implement the auto changelog that can cover these changes. And am too lazy to notify theses
