### ISSUE TITLE
生息演算资源地图

### ISSUE THREAD

**Issue by inkydragon** [Houdou/prts-map#49]
目前看，部分关卡标记了树木🌳的位置。
希望再接再厉，把几种资源的位置都标记上，最好不同资源间能有所区分。
B站上有一些 UP 做了全地图+全视野的视频，可供参考。

感恩❤️

**Comment by Houdou** [comment]
Ummm，之前并没有特别加工地图里的数据。主要是生息演算很多地图数据都是动态叠进去的

刚刚稍微处理了一下换成了掉落物
这样应该。。好一点？
![image](https://user-images.githubusercontent.com/6690811/215540575-5a47b117-bb68-4750-92e3-4aa8d9bb181f.png)

![image](https://user-images.githubusercontent.com/6690811/215540483-6b6efe6f-36de-48a6-96e2-13025df54238.png)
