### ISSUE TITLE
咋把59区废墟去掉了，之前的活动副本就算关闭了也能查看，只有59区没了

### ISSUE THREAD

**Issue by PureDark** [Houdou/prts-map#5]
因为合约太多了，用地图模拟器来查看选了合约后各个兵种的属性是最方便了、
虽然现在活动结束了，但是我觉得地图模拟器可以保留……

**Comment by Houdou** [comment]
其实主要是要手动加入口，平常自动更新的脚本不会加上这几关。
如果需要的话我这两天可以加上

**Comment by Houdou** [comment]
Done
