### ISSUE TITLE
IS3 pathing strange, Ending 3 missing enemies

### ISSUE THREAD

**Issue by grantwwu** [Houdou/prts-map#52]
Hello!

Thank you again for this wonderful website.

It seems like some of the pathing is off for the Mizuki and Caerula Arbor stages.

For example, 

* Deep cognition stage https://map.ark-nights.com/map/ro2_n_6_2 pathing goes into the corner for no reason for all of the enemies.
* Final boss stage https://map.ark-nights.com/map/ro2_b_6 has no enemies at all

I have not done an exhaustive survey, but I think there may be other broken stages as well.

Let me know if there is anything I can do to help with this issue!

**Comment by Houdou** [comment]
Thank you for reporting the issue~
The map data source changed the encoding of path checkpoint type which breaks the path builder.
I have published a fix yesterday for the loading, and those 2 maps you mentioned should be rendered correctly now, at least for start & end position 🤣 

But seems the pathfinding wasn't fully working. Let me check check shortly.

**Comment by grantwwu** [comment]
Thank you, I think it looks good now! I will keep an eye out for any additional broken stages.
