### ISSUE TITLE
关于路网

### ISSUE THREAD

**Issue by snowmaster1** [Houdou/prts-map#56]
这次集成战略的收藏品路网会给大多数关卡增加额外敌人，但prtsmap内无法进行显示，希望可以补充

**Comment by Houdou** [comment]
@snowmaster1 
有一些具体关卡例子吗？我好找找对应数据验证一下

**Comment by snowmaster1** [comment]
几乎每个普通关都有路网变种，苔手在关卡末尾会出现2个弩手，死囚之夜会下方的红门出3个囚犯，虫虫别回头开局中间就会罚站一个护盾术师之类的

**Comment by snowmaster1** [comment]
死囚之夜下面的红门会出3个囚犯，苔手关卡末尾会出2个弩手，虫虫别回头开局就会罚站一个护盾术师，（每个普通类型的关卡都有路网变种）

**Comment by snowmaster1** [comment]
https://www.bilibili.com/video/BV1bj41197T7/?spm_id_from=333.337.search-card.all.click&vd_source=6038f875db3d40d14e0b631b04a2c9bd 这里就有死囚路网出怪

**Comment by Houdou** [comment]
@snowmaster1 
ok，我找到数据了。我看看怎么呈现比较好

**Comment by Houdou** [comment]
@snowmaster1 
![image](https://github.com/Houdou/prts-map/assets/6690811/f9c21f3f-b62b-475e-b6d0-575405dfcdcd)
更新好了，可以直接在线路里开关
