### ISSUE TITLE
希望增加调节敌人路线动画显示速度的功能

### ISSUE THREAD

**Issue by MediocreRex** [Houdou/prts-map#62]
凤瞳大大晚上好，我是一名集成战略爱好者，在频繁查询map摸轴并深感其实用便捷后，想要提议map增加一个调节路线动画显示速度的功能。
*对于一些移动路线复杂的敌人，出怪红线会很快的走完全程，比如险路勿近（墓碑）、人之光辉（伊祖米克）、哨兵（园丁的异格图），这样会有些目不暇接（比如哨兵关卡内克雷松的鬼魅绕圈走位），需要重复播放路线或者录制视频后调慢播放速度；
**而且人之光辉、哨兵关的boss绕圈后会在同一个点罚站，此时罚站时间会重叠显示，需要认真辨识数字。
图示：
![map](https://github.com/Houdou/prts-map/assets/86241506/7dfb3bc0-c88a-4a36-bd37-d1e1e92dde38)

十分感谢您阅读我冗长的说明，PRTS.Map门下牛马走敬上。

**Comment by Houdou** [comment]
是个好问题，其实线路是有根据总长度适当增加动画展示时长的
只是早期没想到之后会有这么长的（（

我看一下放几档或者默认调长点应该可以

**Comment by Houdou** [comment]
@MediocreRex 

加上了，给了几种预设。如果有需要可以自己定制一下
![image](https://github.com/Houdou/prts-map/assets/6690811/ec7fe6b1-cfd0-4099-b0d3-1deae3bdee5f)
路径下面会有快速切换（从下一条路径动画起生效）
![image](https://github.com/Houdou/prts-map/assets/6690811/8118ea29-0d7d-49b6-a882-82effef8198e)

**Comment by Houdou** [comment]
![image](https://github.com/Houdou/prts-map/assets/6690811/94f127fa-b13a-4b40-88af-f6a36252d7c9)
重叠展示部分已经按照顺序覆盖了，就不会看到上一个时间了

**Comment by MediocreRex** [comment]
完美体验，十分感谢❤另外祝愿凤瞳大大新年快乐O(∩_∩)O
