### ISSUE TITLE
关于生息演算的地图矿显示出错

### ISSUE THREAD

**Issue by windhug** [Houdou/prts-map#64]
发现在乱石岗的那张图，亲自测试在O2 N2 C3 C4也会产生铁矿，所以总共有5处随机点生成。
如在prts map这算是正常操作，请无视这项回报，非常感谢。

**Comment by Houdou** [comment]
@windhug 
生息演算有通过随机路线开启资源点的行为。
如果需要切换随机组的话，看一下是不是下面路线中有可选分支？

**Comment by Houdou** [comment]
![image](https://github.com/Houdou/prts-map/assets/6690811/7311c983-b999-46d6-8f02-5c49e1fedb0b)
![image](https://github.com/Houdou/prts-map/assets/6690811/1c77dfa2-bcad-4f6a-a24a-10bf81b2e706)
分别是灌木丛和两组铁矿随机组合
