### ISSUE TITLE
生息演算地图缺少 苦难河床

### ISSUE THREAD

**Issue by NaCl7458** [Houdou/prts-map#65]
我来回检查了十几遍，已确认目前并没有收录这张地图
这是一个冲突区关卡，我还没有开打，本来寄希望于prts map
也许在不久后我将可以得到这一关卡的准确情报，让我能够确保万无一失成功通过

**Comment by Houdou** [comment]
@NaCl7458 
不好意思春节没有看消息

https://map.ark-nights.com/map/sandbox_1_78
不是这个嘛？

**Comment by NaCl7458** [comment]
当时应该的确没有，我翻了好多遍的
也因此让我想请求一个搜索地图的功能
日后会有可能加入嘛
