### ISSUE TITLE
生息演算查看矿牢爬行会导致标签页未响应

### ISSUE THREAD

**Issue by Creeperac** [Houdou/prts-map#67]
![image](https://github.com/Houdou/prts-map/assets/110230535/04234c5e-cf3c-47d3-bd4e-7f42a411e528)
<img width="926" alt="abafb39375aed98ec33a269f10ef227f" src="https://github.com/Houdou/prts-map/assets/110230535/80d77d89-bf30-45fe-8879-3306b95c2d3d">
可以一瞬间看见地图，偶尔可以看见地图上的装置。然而开始加载敌人的时候标签页就会未响应。

**Comment by Houdou** [comment]
不好意思这两周身体不太好没怎么看
我估计是有哪个巡径出问题卡死了，这两天修一下

**Comment by Houdou** [comment]
已经找到问题了，之前的巡经算法在这个尺寸的地图上有问题
改了之后我今天再看一下有没有其他影响就发上来
