### ISSUE TITLE
[地图错误]H6-4地图错误

### ISSUE THREAD

**Issue by chenshaoju** [Houdou/prts-map#7]
地址：
https://map.ark-nights.com/map/hard_06-04

详见下图：
![1](https://user-images.githubusercontent.com/515763/72216591-b7cb3500-355d-11ea-824b-4534e379d3fd.png)

上图中的两个箭头所指的位置并不能放干员。

望修正，感谢。

**Comment by Houdou** [comment]
@chenshaoju 这个数据应该是用锁地板的符文做的，我回去看看是写进关卡里了还是什么情况
