### ISSUE TITLE
Page load problems

### ISSUE THREAD

**Issue by Prurite** [Houdou/prts-map#9]
Sometimes when I try to access the map pages directly from the address bar ( like https://map.ark-nights.com/map ) it responds really slow and sometimes responds a 404 error like the following pic
![图片](https://user-images.githubusercontent.com/44775584/75239146-1fcb9700-57fd-11ea-922a-274a88bbebf2.png)

**Comment by Houdou** [comment]
Sorry, forgot to handle the routing. (the 404.html trick)
Fixed.

**Comment by Houdou** [comment]
For slow response, cuz the server provider should be somewhere in Asia (Probably HK ?). It maybe slow to access from other region.
There is an alternative host:
https://mapen.ark-nights.com

**Comment by Prurite** [comment]
> 
> 
> For slow response, cuz the server provider should be somewhere in Asia (Probably HK ?). It maybe slow to access from other region.
> There is an alternative host:
> https://mapen.ark-nights.com

But I'm using HK relay to access the website... I'm in CN mainland and this relay works fine for websites like Google & Github.

**Comment by Houdou** [comment]
Then mapen one suppose to be faster, you can try that see if it helps
